apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goi-ingress
  namespace: goi
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: goi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goi-ui
                port:
                  number: 80

